CREATE TABLE roles (
    id CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    role_name VARCHAR(255) NOT NULL UNIQUE,
    role_desc VARCHAR(255) NOT NULL,
    access_permission VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
